### ISSUE TITLE
Git not found

### ISSUE THREAD

**Issue by ghost** [bitmovin/bitcodin-php#3]
I tried using the composer install but  composer kept replying with git not found. It seems to not be able to get the package from the provided url. All I did was create the composer.json document, added the require from the front page and right clicked the file and clicked composer install. Am I doing anything wrong.

**Comment by akopper** [comment]
Hi constashare,
To make this dependency work, you gonna have to install the git commandline tools (https://git-scm.com/). Composer utilizes the git command to download the sources to your local filesystem.

**Comment by ghost** [comment]
I thought that might have been the problem. Anyways, this worked and thank you!
