### ISSUE TITLE
Guzzle Library ^6.1

### ISSUE THREAD

**Issue by UltraSimplified** [bitmovin/bitcodin-php#4]
I'm trying to use Bitcodin on a Laravel based web application that is already heavily dependent on the **Guzzle** framework (v 6.1). Adding bitcoding to composer.json triggers the following error:
- bitmovin/bitcodin-php dev-master requires guzzlehttp/guzzle ~5.2 -> satisfiable by guzzlehttp/guzzle[5.2.0, 5.3.0, 5.3.x-dev] but these conflict with your requirements or minimum-stability.

Is it possible to upgrade bitcodin's dependency or are there specific changes between guzzle 5.2 and 6.1 that break bitcodin'?

**Comment by SInCE** [comment]
thank you for your feedback! 
As it is an upgrade to a new major version of guzzle, it is quite likely that there are backward incompatible changes. However, we will check that and see what we can do :) Stay tuned!

**Comment by UltraSimplified** [comment]
Cheers! I'm going to try and adapt some of the code of this library to work in our app — if that's okay with you! I'll feedback if I come across any major incompatibilities.

**Comment by SInCE** [comment]
Sure, feel free to do so :) I think the best way would be to fork that repository. This way, if there is a new version available in the mean time, you can easily switch between our current version, and your altered one just by updating you composer-dependencies.
I'm looking forward to your pull request :)

**Comment by UltraSimplified** [comment]
Great suggestion. I'll do that!

**Comment by Syrome** [comment]
I've noticed after upgrading to ~6.0 of Guzzle that the namespaces have changed in lib/ApiResource. It's looking for GuzzleHttp\Message\Response, whereas the new namespace in 6.0 is GuzzleHttp\Psr7\Response.

So, it seems like there are some BC breaks between 5 and 6 of Guzzle. That being said, I await a new release while I fork and fix this to keep our application working.

UPDATE: Changed that one line and my application works now. I do not make use of the entire bitmovin library, so perhaps there are more BC breaks, but its working with Guzzle 6 for me now.

**Comment by HankBrown** [comment]
I do not yet have the composer/php smarts to cope.
Sounds like you guys have workarounds. I am clueless.

```
$ composer require mailjet/mailjet-apiv3-php
Using version ^1.1 for mailjet/mailjet-apiv3-php
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install mailjet/mailjet-apiv3-php v1.1.7
    - Conclusion: don't install mailjet/mailjet-apiv3-php v1.1.6
    - Conclusion: don't install mailjet/mailjet-apiv3-php v1.1.5
    - Conclusion: don't install mailjet/mailjet-apiv3-php v1.1.4
    - Conclusion: don't install mailjet/mailjet-apiv3-php v1.1.3
    - Conclusion: don't install mailjet/mailjet-apiv3-php v1.1.2
    - Conclusion: don't install mailjet/mailjet-apiv3-php v1.1.1
    - Conclusion: remove guzzlehttp/guzzle 5.3.1
    - Installation request for mailjet/mailjet-apiv3-php ^1.1 -> satisfiable by mailjet/mailjet-apiv3-php[v1.1.0, v1.1.1, v1.1.2, v1.1.3, v1.1.4, v1.1.5, v1.1.6, v1.1.7].
    - Conclusion: don't install guzzlehttp/guzzle 5.3.1
    - mailjet/mailjet-apiv3-php v1.1.0 requires guzzlehttp/guzzle ~6.0|5.3 -> satisfiable by guzzlehttp/guzzle[5.3.0, 6.0.0, 6.0.1, 6.0.2, 6.1.0, 6.1.1, 6.2.0, 6.2.1, 6.2.2].
    - Can only install one of: guzzlehttp/guzzle[5.3.0, 5.3.1].
    - Can only install one of: guzzlehttp/guzzle[6.0.0, 5.3.1].
    - Can only install one of: guzzlehttp/guzzle[6.0.1, 5.3.1].
    - Can only install one of: guzzlehttp/guzzle[6.0.2, 5.3.1].
    - Can only install one of: guzzlehttp/guzzle[6.1.0, 5.3.1].
    - Can only install one of: guzzlehttp/guzzle[6.1.1, 5.3.1].
    - Can only install one of: guzzlehttp/guzzle[6.2.0, 5.3.1].
    - Can only install one of: guzzlehttp/guzzle[6.2.1, 5.3.1].
    - Can only install one of: guzzlehttp/guzzle[6.2.2, 5.3.1].
    - Installation request for guzzlehttp/guzzle (locked at 5.3.1) -> satisfiable by guzzlehttp/guzzle[5.3.1].
Installation failed, reverting ./composer.json to its original content.

```

Pretty simple project at this point, using Yii2 framework.
Wanted to use mailjet transactional mail service with bitmovin.
Sigh.

```
$ cat composer.json
{
    "name": "bh",
    "description": "HankBrown",
    "keywords": ["private"],
    "homepage": "https://mysite.com/",
    "type": "project",
    "license": "BSD-3-Clause",
    "minimum-stability": "stable",
    "require": {
        "php": ">=5.4.0",
        "yiisoft/yii2": ">=2.0.6",
        "yiisoft/yii2-bootstrap": "*",
        "yiisoft/yii2-swiftmailer": "*",
        "mdmsoft/yii2-admin": "~2.0",
        "bitmovin/bitcodin-php": "1.14.*"
    },
    "require-dev": {
        "yiisoft/yii2-codeception": "*",
        "yiisoft/yii2-debug": "*",
        "yiisoft/yii2-gii": "*",
        "yiisoft/yii2-faker": "*"
    },
    "config": {
        "process-timeout": 1800
    },
    "extra": {
        "asset-installer-paths": {
            "npm-asset-library": "vendor/npm",
            "bower-asset-library": "vendor/bower"
        }
    },
    "scripts": {
        "post-install-cmd": "php init --env=Development --overwrite=n"
    }
}


```

**Comment by ghost** [comment]
I had trouble following this issue. Here is what I did. Same as the guys above, just more details.
https://github.com/bitmovin/bitcodin-php/wiki

Waited some months hoping someone else would clarify.
Eventually worked it out myself.
Then, as I post this, I find https://github.com/bitmovin/bitmovin-php
So what the heck? Why is this project here, is it deprecated?
What is the difference between bitcodin and bitmovin?
